version: '3.9'
services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - app-network
 
networks:
  app-network:
    name: app-network
    driver: bridge
    ipam:
      driver: default
 